/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerMgt;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.text.*;
import java.awt.print.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Printer;
import javax.swing.JTextArea;

/**
 *
 * @author ASAVAH
 */
public class CarDealerMgt extends javax.swing.JFrame {

    double Ford = 265670;
    double BMW = 458760;
    double Porsche = 578990;
    double Aston_Martin = 1578830;
    public CarDealerMgt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLastName = new javax.swing.JTextField();
        jFirstName = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jTown = new javax.swing.JTextField();
        jCustomerID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPostCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboProofofID = new javax.swing.JComboBox<>();
        jDownPayment = new javax.swing.JTextField();
        jDeposit = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jReceipt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jCheckStereoSystem = new javax.swing.JCheckBox();
        jCheckLeatherInterior = new javax.swing.JCheckBox();
        jCheckGPS = new javax.swing.JCheckBox();
        jCheckStandard = new javax.swing.JCheckBox();
        jCheckModified = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jComboSelectCar = new javax.swing.JComboBox<>();
        jCarYear = new javax.swing.JTextField();
        jCarCost = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboTradeinCar = new javax.swing.JComboBox<>();
        jTradeYear = new javax.swing.JTextField();
        jTradeCost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jSubTotal = new javax.swing.JTextField();
        jTax = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPrintButton = new javax.swing.JButton();
        jResetButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JButton();
        jTotalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1386, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Car Dealer Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1130, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Customer Details");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Customer ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("First Name");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Address");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Post Code");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Town");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Down Payment");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Deposit");

        jComboProofofID.setEditable(true);
        jComboProofofID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboProofofID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proof of ID", "Pilot Licence", "Driving Licence", "Student ID", "Passport" }));
        jComboProofofID.setName(""); // NOI18N
        jComboProofofID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboProofofIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel10))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTown, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboProofofID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDownPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboProofofID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jDownPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel5))
                .addGap(106, 106, 106))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 620, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 490, 370));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jCheckStereoSystem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckStereoSystem.setText("Stereo System");
        jCheckStereoSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckStereoSystemActionPerformed(evt);
            }
        });

        jCheckLeatherInterior.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckLeatherInterior.setText("Leather Interior");
        jCheckLeatherInterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckLeatherInteriorActionPerformed(evt);
            }
        });

        jCheckGPS.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckGPS.setText("Global Positioning System");

        jCheckStandard.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckStandard.setText("Standard");
        jCheckStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckStandardActionPerformed(evt);
            }
        });

        jCheckModified.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckModified.setText("Modified");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckStereoSystem)
                    .addComponent(jCheckLeatherInterior)
                    .addComponent(jCheckGPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckStandard)
                    .addComponent(jCheckModified))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckStereoSystem)
                    .addComponent(jCheckStandard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckLeatherInterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckGPS)
                    .addComponent(jCheckModified))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 280, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jComboSelectCar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboSelectCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Car", "Ford", "BMW", "Porsche" }));
        jComboSelectCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelectCarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Year");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Cost");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboSelectCar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(jCarCost))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboSelectCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCarCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 150, 130));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jComboTradeinCar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboTradeinCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trade in Car" }));
        jComboTradeinCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTradeinCarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Year");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Cost");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTradeYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jTradeCost))
                .addGap(54, 54, 54))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboTradeinCar, 0, 151, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jComboTradeinCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTradeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTradeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 180, 130));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Tax");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Sub Total");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setText("Total");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 630, 160));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPrintButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPrintButton.setText("Print");
        jPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintButtonActionPerformed(evt);
            }
        });

        jResetButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jResetButton.setText("Reset");
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });

        jExitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jTotalButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTotalButton.setText("Total");
        jTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPrintButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 490, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboProofofIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProofofIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProofofIDActionPerformed

    private void jCheckStereoSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckStereoSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckStereoSystemActionPerformed

    private void jCheckLeatherInteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckLeatherInteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckLeatherInteriorActionPerformed

    private void jCheckStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckStandardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckStandardActionPerformed

    private void jPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintButtonActionPerformed
        try {
            jReceipt.print();
        } catch (PrinterException ex){
            Logger.getLogger(CarDealerMgt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPrintButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        JTextField cleartext = null;
        
        try{
        for (Component c:jPanel3.getComponents()){
        if (c.getClass().toString().contains("javax.swing.JTextField")){
            cleartext = (JTextField)c;
            cleartext.setText("");
            jCarCost.setText("");
            jReceipt.setText("");
            jTax.setText("");
            jSubTotal.setText("");
            jTotal.setText("");
            jCarYear.setText("");
            jCarCost.setText("");
            jTradeYear.setText("");
            jTradeCost.setText("");
            jComboSelectCar.setSelectedItem("Select a Car");
            jComboTradeinCar.setSelectedItem("Trade in Car");
            jCheckStereoSystem.setSelected(true);
            jCheckLeatherInterior.setSelected(true);
            jCheckGPS.setSelected(true);
            jCheckStandard.setSelected(true);
            jCheckModified.setSelected(true);
            
        }
        }
        } catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Confirm if you want to reset" );
        }
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        cCustomer iExit = new cCustomer();
        try{
            iExit.iExitSystem();
        } catch (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Confirm if you want to exit" );
        }
        
    }//GEN-LAST:event_jExitButtonActionPerformed
    public double mcTax = 0.10;
    public double cFindTax(double cAmount){
        double FindTax = cAmount * mcTax;
        return FindTax;
    }
    private void jTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalButtonActionPerformed
        Car_Accessory Accessory = new Car_Accessory();
        //calculate total and tax if one is not trading in car
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("Trade in Car")){
            
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("Trade in Car")){
            
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("Trade in Car")){
            
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("Trade in Car")){
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        //=====================================Trading in car with 1-5000 mileage==============================================================
        
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("1 - 5000")){
           Ford = Ford - 50000;
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("1 - 5000")){
           BMW = BMW - 50000; 
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("1 - 5000")){
            Porsche = Porsche - 50000;
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("1 - 5000")){
           Aston_Martin = Aston_Martin - 50000;
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        //==============================================Trading in car with 50001-20000 mileage===================================================
        
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("5001 - 20000")){
           Ford = Ford - 25000;
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("5001 - 20000")){
           BMW = BMW - 25000; 
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("5001 - 20000")){
           Porsche = Porsche - 25000; 
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("5001 - 20000")){
           Aston_Martin = Aston_Martin - 25000;
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        //==============================================Trading in car with 20001 - 50000 mileage===================================================
        
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("20001 - 50000")){
           Ford = Ford - 20000; 
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("20001 - 50000")){
            BMW = BMW - 20000;
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("20001 - 50000")){
           Porsche = Porsche - 20000; 
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("20001 - 50000")){
           Aston_Martin = Aston_Martin - 20000; 
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        //=============================================Trading in car with 50001-100000 mileage======================================================
        
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("50001 - 100000")){
           Ford = Ford - 15000; 
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("50001 - 100000")){
           BMW = BMW - 15000;
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("50001 - 100000")){
           Porsche = Porsche - 15000; 
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("50001 - 100000")){
           Aston_Martin = Aston_Martin - 15000;
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        //==================================================Trading in car with 100001 - 500000 mileage========================================
        
        if (jComboSelectCar.getSelectedItem().equals("Ford") && jComboTradeinCar.getSelectedItem().equals("100001 - 500000")){
           Ford = Ford - 10000;
           String iSubTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Ford + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Ford + Accessory.getAmount() + cFindTax(Ford + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("BMW") && jComboTradeinCar.getSelectedItem().equals("100001 - 500000")){
           BMW = BMW - 10000; 
           String iSubTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(BMW + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", BMW + Accessory.getAmount() + cFindTax(BMW + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Porsche") && jComboTradeinCar.getSelectedItem().equals("100001 - 500000")){
           Porsche = Porsche - 10000;  
           String iSubTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Porsche + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Porsche + Accessory.getAmount() + cFindTax(Porsche + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        
        if (jComboSelectCar.getSelectedItem().equals("Aston_Martin") && jComboTradeinCar.getSelectedItem().equals("100001 - 500000")){
           Aston_Martin = Aston_Martin - 10000;
           String iSubTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount());
           String iTax = String.format("Ksh%.2f", cFindTax(Aston_Martin + Accessory.getAmount()));
           String iTotal = String.format("Ksh%.2f", Aston_Martin + Accessory.getAmount() + cFindTax(Aston_Martin + Accessory.getAmount()));
           jTax.setText(iTax);
           jSubTotal.setText(iSubTotal);
           jTotal.setText(iTotal);
       }
        //======================================Receipt====================================================================================
        jReceipt.setText("\tCar Dealer Management System" + "\n" +
        "-------------------------------------" +"\n");
        jReceipt.setText("Customer ID" + "\t\t\t" + jCustomerID.getText() +"\n");
        jReceipt.setText("First Name" + "\t\t\t" + jFirstName.getText() +"\n");
        jReceipt.setText("Last Name" + "\t\t\t" + jLastName.getText() +"\n");
        jReceipt.setText("Address" + "\t\t\t" + jAddress.getText() +"\n");
        jReceipt.setText("Post Code" + "\t\t\t" + jPostCode.getText() +"\n");
        jReceipt.setText("Proof of ID" + "\t\t\t" + jComboProofofID.getSelectedItem() +"\n");
        jReceipt.setText("Town" + "\t\t\t" + jTown.getText() +"\n");
        jReceipt.setText("Customer ID" + "\t\t\t" + jCustomerID.getText() +"\n");
        jReceipt.setText("---------------------------------------------------------" + "\n");
        jReceipt.setText("Deposit" + "\t\t\t" + jDeposit.getText() +"\n");
        jReceipt.setText("Down Payment" + "\t\t\t" + jDownPayment.getText() +"\n");
        jReceipt.setText("Type of Car" + "\t\t\t" + jComboSelectCar.getSelectedItem() +"\n");
        
        jReceipt.setText("Year" + "\t\t\t" + jCarYear.getText() +"\n");
        jReceipt.setText("Cost" + "\t\t\t" + jCarCost.getText() +"\n");
        jReceipt.setText("---------------------------------------------------------" + "\n");
        jReceipt.setText("Tax" + "\t\t\t" + jTax.getText() +"\n");
        jReceipt.setText("Sub Total" + "\t\t\t" + jSubTotal.getText() +"\n");
        jReceipt.setText("Down Payment" + "\t\t\t" + jTotal.getText() +"\n");
        jReceipt.setText("---------------------------------------------------------" + "\n");



    }//GEN-LAST:event_jTotalButtonActionPerformed

    private void jReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jReceiptActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cCars ca = new cCars();
        jComboTradeinCar.addItem(ca.getTrade_In_1());
        jComboTradeinCar.addItem(ca.getTrade_In_2());
        jComboTradeinCar.addItem(ca.getTrade_In_3());
        jComboTradeinCar.addItem(ca.getTrade_In_4());
        jComboTradeinCar.addItem(ca.getTrade_In_5());
        
        jCheckStereoSystem.setSelected(true);
        jCheckLeatherInterior.setSelected(true);
        jCheckGPS.setSelected(true);
        jCheckStandard.setSelected(true);
        jCheckModified.setSelected(true);

    }//GEN-LAST:event_formWindowActivated

    private void jComboSelectCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSelectCarActionPerformed
       
       
       if (jComboSelectCar.getSelectedItem().equals("Ford")){
           String Car = String.format("Ksh%.2f", Ford);
           jCarCost.setText(Car);
           jCarYear.setText("2018");
       }
       
       if (jComboSelectCar.getSelectedItem().equals("BMW")){
           String Car = String.format("Ksh%.2f", BMW);
           jCarCost.setText(Car);
           jCarYear.setText("2018");
       }
       
       if (jComboSelectCar.getSelectedItem().equals("Porsche")){
           String Car = String.format("Ksh%.2f", Porsche);
           jCarCost.setText(Car);
           jCarYear.setText("2018");
       }
       
       if (jComboSelectCar.getSelectedItem().equals("Aston_Martin")){
           String Car = String.format("Ksh%.2f", Aston_Martin);
           jCarCost.setText(Car);
           jCarYear.setText("2018");
       }
    }//GEN-LAST:event_jComboSelectCarActionPerformed

    private void jComboTradeinCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTradeinCarActionPerformed
        if (jComboTradeinCar.getSelectedItem().equals("1 - 5000")){
            jTradeCost.setText("50000");
            jTradeYear.setText("2018");
        }
        
        if (jComboTradeinCar.getSelectedItem().equals("5001 - 20000")){
            jTradeCost.setText("25000");
            jTradeYear.setText("2018");
        }
        
        if (jComboTradeinCar.getSelectedItem().equals("20001 - 50000")){
            jTradeCost.setText("20000");
            jTradeYear.setText("2018");
        }
        
        if (jComboTradeinCar.getSelectedItem().equals("50001 - 100000")){
            jTradeCost.setText("15000");
            jTradeYear.setText("2018");
        }
        
        if (jComboTradeinCar.getSelectedItem().equals("100001 - 500000")){
            jTradeCost.setText("10000");
            jTradeYear.setText("2018");
        }
        
       //==========================================================================================================
       
       
    }//GEN-LAST:event_jComboTradeinCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarDealerMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarDealerMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarDealerMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarDealerMgt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarDealerMgt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jCarCost;
    private javax.swing.JTextField jCarYear;
    private javax.swing.JCheckBox jCheckGPS;
    private javax.swing.JCheckBox jCheckLeatherInterior;
    private javax.swing.JCheckBox jCheckModified;
    private javax.swing.JCheckBox jCheckStandard;
    private javax.swing.JCheckBox jCheckStereoSystem;
    private javax.swing.JComboBox<String> jComboProofofID;
    private javax.swing.JComboBox<String> jComboSelectCar;
    private javax.swing.JComboBox<String> jComboTradeinCar;
    private javax.swing.JTextField jCustomerID;
    private javax.swing.JTextField jDeposit;
    private javax.swing.JTextField jDownPayment;
    private javax.swing.JButton jExitButton;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jPostCode;
    private javax.swing.JButton jPrintButton;
    private javax.swing.JTextField jReceipt;
    private javax.swing.JButton jResetButton;
    private javax.swing.JTextField jSubTotal;
    private javax.swing.JTextField jTax;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jTotalButton;
    private javax.swing.JTextField jTown;
    private javax.swing.JTextField jTradeCost;
    private javax.swing.JTextField jTradeYear;
    // End of variables declaration//GEN-END:variables
}
